language: en

pipeline:
  - name: "SpacyNLP"
    case_sensitive: false
  - name: "SpacyEntityExtractor"
  - name: "SpacyTokenizer"
  - name: "RegexFeaturizer"
  - name: "SpacyFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "SklearnIntentClassifier"
    url: "http://localhost:8000"
    locale: "en_IN"
    timezone: "Asia/Kolkata"
    dimensions: ["time", "number"]

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
